"""Evaluation-only counterfactual probe for single-action mode averaging.

The probe never replaces the action executed by the player.  It sends three fixed 898-D
structured observations through the frozen policy in a side forward pass: a corridor centred on
body-forward and the same corridor shifted by +/- ``offset_deg``.  Left/right are exact reflected
pairs under the deployed structured-observation contract; the centre is their arithmetic
midpoint.  This makes the test reproducible and separates policy sensitivity from simulator reset
noise, but the midpoint's obstacle-token ordering is a counterfactual interpolation rather than a
claim that the perception selector would emit those exact bytes at a geometric tie.
"""

from __future__ import annotations

import json
import math
import os
from pathlib import Path

import torch

from aerial_gym.rl_training.rl_games.ppo_update_safety import (
    mirror_navrl_actions,
    mirror_navrl_structured_observation,
)


SCHEMA_VERSION = 1
AXES = ("x", "y", "z", "yaw")

# Predeclared before policy measurement.  These are mechanism gates, not a replacement-policy
# gate and not an outcome/capture claim.
GATES = {
    "reflection_max_abs_action": 0.15,
    "symmetric_horizontal_speed_max_mps": 0.25,
    "perturbed_horizontal_speed_min_mps": 0.75,
    "symmetric_abs_lateral_max": 0.10,
    "perturbed_abs_lateral_min": 0.25,
    "near_zero_horizontal_speed_mps": 0.25,
}


def _layout():
    hbeams = int(os.environ.get("NAVRL_LIDAR_HBEAMS", "72"))
    vbeams = int(os.environ.get("NAVRL_LIDAR_VBEAMS", "4"))
    max_obstacles = int(os.environ.get("NAVRL_MAX_OBSTACLES", "8"))
    static_dim = hbeams * vbeams
    obstacle_size = 5 * max_obstacles * 12
    robot_size = 5 * 10
    target_size = 5 * 16
    return hbeams, vbeams, max_obstacles, static_dim, obstacle_size, robot_size, target_size


def _left_fixture(*, device, dtype, offset_deg=5.0):
    """Build one physically interpretable, slightly-left corridor observation."""
    hbeams, vbeams, max_obstacles, static_dim, obstacle_size, robot_size, target_size = _layout()
    total = static_dim + obstacle_size + robot_size + target_size
    obs = torch.zeros((1, total), device=device, dtype=dtype)

    # Static scan: no-return=1, with two 4 m surfaces forming an opening whose centre is shifted
    # left.  Two adjacent horizontal beams per surface approximate a finite-width bar.
    scan = obs[:, :static_dim].view(1, vbeams, hbeams)
    scan.fill_(1.0)
    bin_deg = 360.0 / hbeams
    pair_angles = (12.0 + offset_deg, -12.0 + offset_deg)
    for angle in pair_angles:
        idx = int(round((180.0 - angle) / bin_deg)) % hbeams
        scan[:, :, idx] = 4.0 / 12.0
        scan[:, :, (idx + 1) % hbeams] = 4.0 / 12.0

    # Structured obstacle histories use the documented NavRL token schema.  Keep pair order fixed;
    # the right arm is generated by the canonical mirror function rather than independently sorted.
    offset = static_dim
    obstacles = obs[:, offset : offset + obstacle_size].view(1, 5, max_obstacles, 12)
    for slot, angle in enumerate(pair_angles):
        radius = math.radians(angle)
        r = 4.0
        radial_sigma = 0.04 + 0.02 * r
        lateral_sigma = 0.05 + r * math.tan(math.radians(5.0))
        feat = torch.tensor(
            [
                r * math.cos(radius) / 12.0,
                r * math.sin(radius) / 12.0,
                0.0,
                0.0, 0.0, 0.0,
                0.30 / 12.0,
                1.0 - r / 12.0,
                radial_sigma**2 / 12.0**2,
                lateral_sigma**2 / 12.0**2,
                0.12 / 12.0**2,
                1.0,
            ],
            device=device,
            dtype=dtype,
        )
        obstacles[:, :, slot] = feat

    offset += obstacle_size
    robot = obs[:, offset : offset + robot_size].view(1, 5, 10)
    robot[..., 8] = 1.0 / 3.0  # level at the nominal flight altitude
    robot[..., 9] = 1.0        # valid

    offset += robot_size
    target = obs[:, offset : offset + target_size].view(1, 5, 16)
    target[..., 0] = 8.0 / 20.0  # stationary, visible target 8 m forward
    target[..., 12] = 1.0
    target[..., 13] = 1.0
    target[..., 15] = 0.30 / 12.0
    return obs


def build_probe_observations(reference_obs, *, offset_deg=5.0):
    """Return centre/left/right fixtures on the reference tensor's device and dtype."""
    if not isinstance(reference_obs, torch.Tensor) or reference_obs.ndim != 2:
        raise ValueError("reference_obs must be a [batch, features] tensor")
    left = _left_fixture(
        device=reference_obs.device, dtype=reference_obs.dtype, offset_deg=offset_deg
    )
    if left.shape[1] != reference_obs.shape[1]:
        raise ValueError(
            "mode probe supports the base structured schema only: fixture=%d runtime=%d"
            % (left.shape[1], reference_obs.shape[1])
        )
    right = mirror_navrl_structured_observation(left)
    centre = 0.5 * (left + right)
    # Fail closed before policy inference: a drifted mirror/schema invalidates every comparison.
    centre_error = float(
        (mirror_navrl_structured_observation(centre) - centre).abs().max().item()
    )
    pair_error = float(
        (mirror_navrl_structured_observation(left) - right).abs().max().item()
    )
    if centre_error > 1e-7 or pair_error > 1e-7:
        raise RuntimeError("mode-probe fixture reflection contract failed")
    return {"symmetric": centre, "left": left, "right": right}, {
        "symmetric_reflection_max_abs": centre_error,
        "left_right_reflection_max_abs": pair_error,
    }


def model_outputs(result):
    """Extract bounded deterministic action and available Gaussian parameters."""
    action = result.get("deterministic_actions", result.get("mus"))
    if not isinstance(action, torch.Tensor) or action.ndim != 2 or action.shape[1] != 4:
        raise RuntimeError("policy did not expose a four-axis deterministic action")
    mu = result.get("mus")
    sigma = result.get("sigmas")
    return {
        "action": action.detach(),
        "mu": mu.detach() if isinstance(mu, torch.Tensor) and mu.shape == action.shape else None,
        "sigma": (
            sigma.detach()
            if isinstance(sigma, torch.Tensor) and sigma.shape == action.shape
            else None
        ),
    }


class ModeProbeRecorder:
    def __init__(self, output_path, *, max_velocity_mps, offset_deg=5.0):
        self.output_path = Path(output_path)
        self.max_velocity = float(max_velocity_mps)
        self.offset_deg = float(offset_deg)
        if not math.isfinite(self.max_velocity) or self.max_velocity <= 0.0:
            raise ValueError("max_velocity_mps must be finite and positive")
        self.samples = 0
        self.fixture_contract = None
        self.sum = {
            arm: {key: torch.zeros(4, dtype=torch.float64) for key in ("action", "mu", "sigma")}
            for arm in ("symmetric", "left", "right")
        }
        self.available = {"action": True, "mu": True, "sigma": True}
        self.near_zero = {arm: 0 for arm in self.sum}

    def record(self, outputs, fixture_contract):
        if set(outputs) != set(self.sum):
            raise ValueError("mode probe requires symmetric/left/right outputs")
        self.fixture_contract = dict(fixture_contract)
        batch = None
        for arm, values in outputs.items():
            action = values["action"]
            if not torch.isfinite(action).all():
                raise RuntimeError("mode probe observed non-finite deterministic action")
            batch = int(action.shape[0]) if batch is None else batch
            if int(action.shape[0]) != batch:
                raise RuntimeError("mode probe arm batch sizes differ")
            for key in ("action", "mu", "sigma"):
                value = values[key]
                if value is None:
                    self.available[key] = False
                    continue
                if not torch.isfinite(value).all():
                    raise RuntimeError("mode probe observed non-finite %s" % key)
                self.sum[arm][key] += value.double().sum(dim=0).cpu()
            horizontal = action[:, :2].norm(dim=1) * self.max_velocity
            self.near_zero[arm] += int(
                (horizontal <= GATES["near_zero_horizontal_speed_mps"]).sum().item()
            )
        self.samples += int(batch or 0)

    def payload(self):
        if self.samples <= 0 or self.fixture_contract is None:
            raise RuntimeError("mode probe has no samples")

        def mean(arm, key):
            if not self.available[key]:
                return None
            return [float(v / self.samples) for v in self.sum[arm][key]]

        arms = {}
        for arm in self.sum:
            action = mean(arm, "action")
            arms[arm] = {
                "deterministic_action_mean": action,
                "latent_mu_mean": mean(arm, "mu"),
                "sigma_mean": mean(arm, "sigma"),
                "command_xy_mean_mps": [
                    action[0] * self.max_velocity,
                    action[1] * self.max_velocity,
                ],
                "horizontal_speed_from_mean_mps": math.hypot(action[0], action[1])
                * self.max_velocity,
                "near_zero_horizontal_rate": self.near_zero[arm] / self.samples,
            }

        left = torch.tensor(arms["left"]["deterministic_action_mean"]).view(1, 4)
        right = torch.tensor(arms["right"]["deterministic_action_mean"]).view(1, 4)
        reflected_left = mirror_navrl_actions(left)
        reflection_error = (right - reflected_left).abs().view(-1).tolist()
        symmetric = arms["symmetric"]
        perturb_speed = 0.5 * (
            arms["left"]["horizontal_speed_from_mean_mps"]
            + arms["right"]["horizontal_speed_from_mean_mps"]
        )
        perturb_abs_y = 0.5 * (abs(float(left[0, 1])) + abs(float(right[0, 1])))
        lateral_opposite = float(left[0, 1] * right[0, 1]) < 0.0
        quality = max(reflection_error) <= GATES["reflection_max_abs_action"]
        checks = {
            "policy_reflection_quality": quality,
            "symmetric_horizontal_stall": symmetric["horizontal_speed_from_mean_mps"]
            <= GATES["symmetric_horizontal_speed_max_mps"],
            "perturbations_restore_motion": perturb_speed
            >= GATES["perturbed_horizontal_speed_min_mps"],
            "symmetric_lateral_near_zero": abs(
                symmetric["deterministic_action_mean"][1]
            ) <= GATES["symmetric_abs_lateral_max"],
            "perturbed_lateral_decisive": perturb_abs_y
            >= GATES["perturbed_abs_lateral_min"],
            "perturbed_lateral_signs_opposite": lateral_opposite,
        }
        mechanism = all(value for key, value in checks.items() if key != "policy_reflection_quality")
        if not quality:
            verdict = "INCONCLUSIVE_POLICY_CHIRALITY"
        elif mechanism:
            verdict = "MODE_AVERAGING_SUPPORTED_FOR_COUNTERFACTUAL_FIXTURE"
        else:
            verdict = "MODE_AVERAGING_NOT_SUPPORTED_FOR_COUNTERFACTUAL_FIXTURE"
        return {
            "schema_version": SCHEMA_VERSION,
            "probe": "frozen_policy_symmetric_corridor_counterfactual",
            "decision_authority": "diagnostic_only_no_training_or_replacement_authority",
            "samples": self.samples,
            "independent_fixture_count": 1,
            "offset_deg": self.offset_deg,
            "max_velocity_mps": self.max_velocity,
            "fixture_contract": self.fixture_contract,
            "preregistered_gates": dict(GATES),
            "arms": arms,
            "pair": {
                "right_minus_reflected_left_abs": reflection_error,
                "perturbed_horizontal_speed_mean_mps": perturb_speed,
                "perturbed_abs_lateral_mean": perturb_abs_y,
            },
            "checks": checks,
            "verdict": verdict,
            "limitations": [
                "The centre observation is the exact arithmetic midpoint of a mirrored pair; "
                "obstacle-token ordering at a real geometric tie may emit different bytes.",
                "This side forward-pass does not execute commands or measure capture/crash outcomes.",
                "The reported sample count is repeated inference of one fixed fixture per arm, not "
                "independent environment samples and not a confidence-interval basis.",
                "A positive result motivates a simulator replay or candidate-head ablation; it does "
                "not by itself establish a causal high-density failure mechanism.",
            ],
        }

    def write(self):
        payload = self.payload()
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        if self.output_path.exists():
            raise RuntimeError("refusing to overwrite mode-probe output: %s" % self.output_path)
        tmp = self.output_path.with_name(self.output_path.name + ".tmp")
        tmp.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        tmp.replace(self.output_path)
        return payload
