#!/usr/bin/env python3
"""Audit what acquisition/reacquisition evidence the FROZEN target-motion export holds.

No simulation is run and no raw artifact is modified. Every number is recomputed
from the 48 frozen cells, so the document cannot drift from the evidence.

    python3 tools/build_visibility_reacquisition_audit.py [--check]
"""
from __future__ import annotations
import argparse, glob, json, os, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "results/target_motion_e0_e2_evaluation_2026-09-18"
CANON = ROOT / "results/target_motion_e0_e2_2026-09-18/canonical_summary.json"
OUT_MD = ROOT / "docs/results/target_motion_visibility_reacquisition_audit_2026-09-19.md"
OUT_JSON = ROOT / "docs/results/target_motion_visibility_reacquisition_audit_2026-09-19.json"

ARMS = ("E0_static", "E1_cv", "H_historical", "E2_obstacle_aware")
LBL = {"E0_static": "E0 static", "E1_cv": "E1 CV",
       "H_historical": "H historical", "E2_obstacle_aware": "E2 obstacle-aware"}
CLS = ("capture", "crash", "timeout")

# What the preregistered wish-list asked for, against what the export actually holds.
INVENTORY = [
    ("visible -> invisible transitions", "RECORDED_DIRECTLY",
     "target_motion.first_acquisition.<class>.visible_hidden_transitions",
     "navrl_task.py:5525 counts `prev_visible & ~visible & valid_y_now`, i.e. strictly the "
     "visible->hidden direction, and only between two VALID observations."),
    ("invisible -> visible transitions", "DERIVABLE_FROM_FROZEN_DATA",
     "derived from visible_hidden_transitions plus the terminal visibility state",
     "An episode starts hidden, so hidden->visible count equals visible->hidden count, plus one "
     "if the episode ended visible. The terminal visibility flag is NOT exported, so the derived "
     "count is bounded to +/-1 per episode and is not reported as a point value."),
    ("reacquisition count", "DERIVABLE_FROM_FROZEN_DATA",
     "hidden->visible transitions after the first acquisition",
     "Equals the derived hidden->visible count minus the first acquisition, inheriting the same "
     "+/-1 per-episode bound."),
    ("loss duration", "NOT_RECORDED", "-",
     "No per-loss duration accumulator exists anywhere in the task."),
    ("maximum loss duration", "NOT_RECORDED", "-", "Same: no duration state is kept per loss."),
    ("track age", "NOT_RECORDED", "-",
     "search_state carries belief coverage, not a track-age counter."),
    ("lost-track duration", "NOT_RECORDED", "-", "Not accumulated."),
    ("visibility before capture", "RECORDED_DIRECTLY",
     "target_motion.outcome_telemetry.capture.visible_fraction_step_weighted", ""),
    ("visibility before timeout", "RECORDED_DIRECTLY",
     "target_motion.outcome_telemetry.timeout.visible_fraction_step_weighted", ""),
    ("visibility by target-motion arm", "RECORDED_DIRECTLY",
     "canonical_summary.observation_side_visibility.per_arm", ""),
    ("first acquisition latency", "RECORDED_DIRECTLY",
     "first_acquisition.<class>.first_visible_step_{mean,median,p10,p90}",
     "Not on the original wish-list, but present and directly relevant."),
    ("never-acquired rate", "RECORDED_DIRECTLY",
     "first_acquisition.<class>.never_acquired_rate",
     "Not on the original wish-list; it turns out to carry the clearest signal."),
]


def collect():
    out = {}
    for arm in ARMS:
        for c in CLS:
            E = N = CN = T = A = 0
            fsum = 0.0
            for f in glob.glob(str(RAW / f"{arm}__*bars__seed*/result.json")):
                fa = json.loads(Path(f).read_text())["target_motion"]["first_acquisition"][c]
                e = int(fa["episodes"]); E += e
                N += int(fa["never_acquired"]); CN += int(fa["camera_never_acquired"])
                a = int(fa["acquired"]); A += a
                if fa["first_visible_step_mean"] is not None:
                    fsum += fa["first_visible_step_mean"] * a
                T += int(fa["visible_hidden_transitions"])
            out[f"{arm}|{c}"] = dict(
                episodes=E, never_acquired=N, never_acquired_rate=(N / E if E else None),
                camera_never_acquired=CN, camera_never_acquired_rate=(CN / E if E else None),
                acquired=A, first_visible_step_mean=(fsum / A if A else None),
                visible_hidden_transitions=T,
                visible_hidden_transitions_per_episode=(T / E if E else None))
    return out


def render(d, canon):
    vis = canon["observation_side_visibility"]["per_arm"]
    L = []; A = L.append
    A("# Target-motion visibility / reacquisition audit — 2026-09-19\n")
    A("Generated by `tools/build_visibility_reacquisition_audit.py` from the 48 frozen cells of "
      "`results/target_motion_e0_e2_evaluation_2026-09-18/`. **No simulation was run and no raw "
      "artifact was modified.** Do not edit by hand.\n")
    A("The question this answers is narrow: *does the frozen export already contain "
      "acquisition/reacquisition evidence, without generating new data?* It partly does, and the "
      "part it contains points somewhere more specific than the visibility fraction did.\n")

    A("## 1. What is actually recorded\n")
    A("| candidate metric | status | source field |")
    A("|---|---|---|")
    for name, status, field, _ in INVENTORY:
        A(f"| {name} | **{status}** | `{field}` |")
    A("")
    for name, status, _, note in INVENTORY:
        if note:
            A(f"* **{name}** — {note}")
    A("")
    A("Nothing was reconstructed beyond what the aggregate export supports. The three duration "
      "metrics are absent outright and are reported as `NOT_RECORDED` rather than approximated.\n")

    A("## 2. Acquisition statistics per arm and outcome class\n")
    A("Pooled over all 12 cells of each arm.\n")
    A("| arm | class | episodes | never acquired | first visible step (mean) | visible→hidden per episode |")
    A("|---|---|---:|---:|---:|---:|")
    for arm in ARMS:
        for c in CLS:
            r = d[f"{arm}|{c}"]
            fv = r["first_visible_step_mean"]
            A(f"| {LBL[arm]} | {c} | {r['episodes']:,} | {r['never_acquired_rate']*100:.2f}% | "
              f"{(f'{fv:.1f}' if fv is not None else '—')} | "
              f"{r['visible_hidden_transitions_per_episode']:.3f} |")
    A("")

    A("## 3. What this changes about the mechanism reading\n")
    e0t = d["E0_static|timeout"]; e1t = d["E1_cv|timeout"]
    ht = d["H_historical|timeout"]; e2t = d["E2_obstacle_aware|timeout"]
    A(f"In **{e0t['never_acquired_rate']*100:.2f}%** of E0 timeout episodes the target was "
      f"**never acquired even once**, against {e1t['never_acquired_rate']*100:.2f}% (E1), "
      f"{ht['never_acquired_rate']*100:.2f}% (H) and {e2t['never_acquired_rate']*100:.2f}% (E2).\n")
    A("That is a different statement from the one the visibility fraction supported. The "
      "step-weighted fraction was consistent with *losing* a target and not getting it back. The "
      "acquisition record says the dominant failure is earlier than that: for a static target the "
      "policy frequently **never makes first contact at all**.\n")
    A("The same ordering appears in the crash class, where every arm does acquire more often than "
      "in timeouts but the arms stay ordered the same way:\n")
    A("| arm | never acquired, crash episodes |")
    A("|---|---:|")
    for arm in ARMS:
        A(f"| {LBL[arm]} | {d[f'{arm}|crash']['never_acquired_rate']*100:.2f}% |")
    A("")
    A("Among captures, acquisition is near-universal in every arm (never-acquired at or below "
      "0.07%), and the arms separate instead on **how quickly** they acquire: "
      + ", ".join(f"{LBL[a]} {d[f'{a}|capture']['first_visible_step_mean']:.1f}" for a in
                  sorted(ARMS, key=lambda a: d[f'{a}|capture']['first_visible_step_mean']))
      + " observation steps to first sight.\n")
    A("Fused and camera acquisition agree exactly in every row, so the camera is the binding "
      "source here; no fusion path rescued an episode the camera missed.\n")

    A("## 4. Bounded interpretation\n")
    A("> The acquisition record is consistent with a **first-contact** rather than purely a "
      "reacquisition account: under this frozen policy, a static target that is not found early is "
      "frequently never found, whereas moving targets generate the relative motion that leads to "
      "first sight. Visibility and acquisition both order the arms the same way as close-approach "
      "success.\n")
    A("This remains an **association**. No mediation or counterfactual experiment was run, and "
      "none is authorised here. In particular this audit does not establish that acquisition "
      "failure *causes* the close-approach difference, because the same target motion that changes "
      "acquisition also changes everything downstream of it.\n")
    A("The pooled step-weighted visibility estimator retains its caveat — it weights longer "
      "episodes more heavily and is not an unconditioned per-episode mean:\n")
    A("| arm | pooled step-weighted visibility |")
    A("|---|---:|")
    for arm in ARMS:
        A(f"| {LBL[arm]} | {vis[arm]['visible_fraction_step_weighted']:.4f} |")
    A("")

    A("## 5. What would still need new data\n")
    A("Loss duration, maximum loss duration and track age are `NOT_RECORDED`. A causal test of the "
      "reacquisition account would need a preregistered experiment that holds first-contact "
      "geometry fixed while varying only target motion — which is new data collection, outside "
      "this task.\n")
    A("```text\nREACQUISITION_TRANSITION_METRICS = PARTIALLY_RECORDED\n"
      "  visible_hidden_transitions      = RECORDED_DIRECTLY\n"
      "  hidden_visible / reacquisition  = DERIVABLE_FROM_FROZEN_DATA (+/-1 per episode)\n"
      "  loss_duration / track_age       = NOT_RECORDED\n```\n")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    d = collect(); canon = json.loads(CANON.read_text())
    md = render(d, canon)
    js = json.dumps({"schema_version": 1, "generated": "2026-09-19",
                     "source": "results/target_motion_e0_e2_evaluation_2026-09-18 (frozen)",
                     "simulation_run": False,
                     "inventory": [{"metric": n, "status": s, "field": f, "note": t}
                                   for n, s, f, t in INVENTORY],
                     "per_arm_outcome": d}, indent=2) + "\n"
    if a.check:
        ok = OUT_MD.exists() and OUT_MD.read_text() == md and OUT_JSON.exists() and OUT_JSON.read_text() == js
        print("audit is current" if ok else "STALE: regenerate"); return 0 if ok else 2
    OUT_MD.write_text(md); OUT_JSON.write_text(js)
    print(f"wrote {OUT_MD.relative_to(ROOT)}\nwrote {OUT_JSON.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
