"""Test whether the Sony5100 calibration candidate, cam0's surveyed position, drone0's GT trajectory and the
frame timestamps are mutually consistent, using HUMAN-reviewed drone0 boxes.

Two independent estimates are computed from reviewed box centres:
  * rotation-only fit (camera position fixed at the surveyed cam0 location; Kabsch on bearing rays)
  * unconstrained PnP whose recovered camera centre is compared with the surveyed position
Frame-time alignments from -3 to +3 frames are evaluated and reported, because the published stamps were
generated by MATLAB VideoReader (CurrentTime after readFrame, edit list of one frame, one frame fewer than the
container) with sync coefficients that were later revised upstream.
Thresholds are fixed here BEFORE any box exists; the tool never edits boxes.
"""
import argparse
import csv
import json
import math
from pathlib import Path

from prepare_eth_ds5 import COMMIT, digests, numeric_table, write_json
from prepare_eth_ds5_review import interpolate_pose

PIXEL_RMS_PASS = 4.0        # px, 1080p; box-centre noise plus 1 cm GT is well below this
CENTRE_DISTANCE_PASS = 2.0  # m between PnP centre and the surveyed cam0 position
MIN_BOXES = 6
ALIGNMENT_SHIFTS = tuple(range(-3, 4))


def load_review(path):
    rows = []
    with open(path, newline="") as handle:
        for r in csv.DictReader(handle):
            if r.get("drone0_visible", "").strip().lower() not in ("yes", "y", "1", "true"):
                continue
            box = [float(r["box_x%d" % 1]), float(r["box_y1"]), float(r["box_x2"]), float(r["box_y2"])]
            if box[2] <= box[0] or box[3] <= box[1]:
                raise ValueError("degenerate box for frame " + r["frame_id"])
            rows.append({"frame_id": int(r["frame_id"]), "opencv_index": int(r["opencv_index"]),
                         "project_timestamp_s": float(r["project_timestamp_s"]), "box_xyxy": box,
                         "centre": [(box[0] + box[2]) / 2, (box[1] + box[3]) / 2]})
    return rows


def camera_rays(pixels, K, dist):
    import cv2
    import numpy as np
    pts = np.asarray(pixels, np.float64).reshape(-1, 1, 2)
    norm = cv2.undistortPoints(pts, np.asarray(K, np.float64), np.asarray(dist, np.float64)).reshape(-1, 2)
    rays = np.concatenate([norm, np.ones((len(norm), 1))], axis=1)
    return rays / np.linalg.norm(rays, axis=1, keepdims=True)


def fit_rotation(rays_cam, rays_world):
    """Kabsch: R minimising sum ||R w - c||^2 over unit rays; returns R (world->camera) and residual degrees."""
    import numpy as np
    c, w = np.asarray(rays_cam), np.asarray(rays_world)
    u, _, vt = np.linalg.svd(c.T @ w)
    d = np.sign(np.linalg.det(u @ vt))
    R = u @ np.diag([1, 1, d]) @ vt
    cosines = np.clip(np.sum((w @ R.T) * c, axis=1), -1, 1)
    return R, np.degrees(np.arccos(cosines))


def reproject(R, camera_xyz, world_points, K, dist):
    import cv2
    import numpy as np
    rvec, _ = cv2.Rodrigues(np.asarray(R, np.float64))
    tvec = -np.asarray(R, np.float64) @ np.asarray(camera_xyz, np.float64)
    pixels, _ = cv2.projectPoints(np.asarray(world_points, np.float64).reshape(-1, 1, 3), rvec, tvec,
                                  np.asarray(K, np.float64), np.asarray(dist, np.float64))
    return pixels.reshape(-1, 2)


def pnp_centre(world_points, pixels, K, dist):
    import cv2
    import numpy as np
    ok, rvec, tvec = cv2.solvePnP(np.asarray(world_points, np.float64).reshape(-1, 1, 3),
                                  np.asarray(pixels, np.float64).reshape(-1, 1, 2),
                                  np.asarray(K, np.float64), np.asarray(dist, np.float64), flags=cv2.SOLVEPNP_SQPNP)
    if not ok:
        raise ValueError("PnP failed")
    R, _ = cv2.Rodrigues(rvec)
    return (-R.T @ tvec.reshape(3)).tolist()


def evaluate(reviewed, pose, camera_xyz, K, dist, period, alignment_shift_frames):
    import numpy as np
    world, pixels, used = [], [], []
    for r in reviewed:
        gt = interpolate_pose(pose, r["project_timestamp_s"] + alignment_shift_frames * period)
        if gt is None:
            continue
        world.append(gt["xyz_m"])
        pixels.append(r["centre"])
        used.append(r["frame_id"])
    if len(world) < MIN_BOXES:
        return {"status": "INSUFFICIENT_REVIEWED_BOXES", "boxes_used": len(world)}
    rays_c = camera_rays(pixels, K, dist)
    rays_w = np.asarray(world) - np.asarray(camera_xyz)
    rays_w = rays_w / np.linalg.norm(rays_w, axis=1, keepdims=True)
    R, angular = fit_rotation(rays_c, rays_w)
    residual = reproject(R, camera_xyz, world, K, dist) - np.asarray(pixels)
    rms = float(math.sqrt(np.mean(np.sum(residual ** 2, axis=1))))
    centre = pnp_centre(world, pixels, K, dist)
    centre_distance = float(np.linalg.norm(np.asarray(centre) - np.asarray(camera_xyz)))
    passed = rms < PIXEL_RMS_PASS and centre_distance < CENTRE_DISTANCE_PASS
    return {"status": "CONSISTENT" if passed else "INCONSISTENT", "boxes_used": len(world), "frame_ids": used,
            "rotation_world_to_camera": np.asarray(R).tolist(), "angular_residual_deg_max": float(angular.max()),
            "pixel_rms": rms, "pixel_residual_max": float(np.abs(residual).max()),
            "pnp_camera_centre_m": centre, "pnp_centre_distance_to_surveyed_m": centre_distance,
            "thresholds": {"pixel_rms": PIXEL_RMS_PASS, "centre_distance_m": CENTRE_DISTANCE_PASS}}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--review-csv", type=Path, required=True)
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--calibration", type=Path, required=True)
    parser.add_argument("--fps", type=float, default=30000 / 1001)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.output.exists():
        raise ValueError("refusing existing output")
    calibration = json.loads(args.calibration.read_text())
    pose = numeric_table(args.dataset / "dataset5/pose/fused_pose.txt", 11)
    camera_lines = (args.dataset / "dataset5/camera-locations/campos.txt").read_text().splitlines()
    camera = next(list(map(float, l.split()[1:])) for l in camera_lines if l.startswith("cam0\t"))
    reviewed = load_review(args.review_csv)
    period = 1.0 / args.fps
    results = {"alignment_shift_%+d" % s: evaluate(reviewed, pose, camera, calibration["K-matrix"], calibration["distCoeff"], period, s)
               for s in ALIGNMENT_SHIFTS}
    consistent = [k for k, v in results.items() if v["status"] == "CONSISTENT"]
    receipt = {"status": "CALIBRATION_CANDIDATE_CONSISTENT" if consistent else "CALIBRATION_CANDIDATE_NOT_VALIDATED",
               "consistent_alignments": consistent, "source_commit": COMMIT, "reviewed_boxes": len(reviewed),
               "review_csv_sha256": digests(args.review_csv)[1], "calibration_sha256": digests(args.calibration)[1],
               "results": results, "tool_sha256": digests(Path(__file__))[1],
               "note": "Consistency of reviewed boxes with K/dist, surveyed position and GT is necessary for using the"
                       " calibration; it does not certify lens distortion beyond the box locations tested."}
    write_json(args.output / "reprojection_check.json", receipt)
    print(json.dumps(receipt, indent=2))


if __name__ == "__main__":
    main()
